# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages', '_subpages']

# Permalinks
permalink:        pretty

# Setup
title:            Intermediate Latin 1
tagline:          'LATN 213'
course_number:    'LATN 213'
section_number:   '01'
semester:         'Fall 2021'
url:              https://libatique.info/LATN213-F21
baseurl:

author:
  name:           'Daniel Libatique'
  url:            https://libatique.info

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/LATN213-F21
